MyPersonal/About/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from. views import about

urlpatterns = [
    url(r'^$', about, name="about" )
]

MyPersonal/Admin/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import edit_tags, login_views, post_edit, LogoutViews, \
    upload_index, register, post_index, post_create, tag_index, create_tags,\
    about_edit
from django.contrib.auth import views as auth_views
app_name = 'Admin'
urlpatterns = [
    url(r'^$', login_views, name='login'),
    url(r'^login/$',login_views, name='login'),
    url(r'^logout/$',LogoutViews.as_view(), name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^posts$',post_index, name='posts'),
    url(r'^posts/([\d]+)/edit/$',post_edit, name="post_edit"),
    url(r'^posts/create/$', post_create, name='post_create'),
    url(r'^tags/$', tag_index, name='tags'),
    url(r'^create_tags',create_tags,name='create_tags'),
    url(r'^tags/([\d]+)/edit/',edit_tags, name='edit_tag'),
    url(r'^about/edit/', about_edit, name='about_edit'),
    url(r'^upload/$', upload_index, name='upload'),
]

MyPersonal/MyPersonal/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, ShowPostsViews, ContactViews
from django.contrib.auth import views



urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/',ContactViews.as_view(), name='contact'),
    url(r'^posts/(?P<slug>\w+)$', ShowPostsViews.as_view(), name='show'),
    url(r'^admin/', include('Admin.urls')),
    url(r'^about/', include('About.urls')),
    url(r'^uploads/',include('upload.urls')),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
]

handler404 = 'MyPersonal.views.page_not_found_view'
handler403 = 'MyPersonal.views.permission_denied_view'
handler500 = 'MyPersonal.views.error_view'

MyPersonal/Admin/templates/partials/navbar.html
<ul id="menu" class="nav navbar-nav">
    <li><a href="/">Blog Home</a></li>
        {%if 'posts/' in request.path %}
        <li class="active">
        {% else %}
        <li>
        {% endif %}
            <a href="{% url 'Admin:posts' %}">Posts</a>
        </li>
        {% if 'tags/' in request.path %}
        <li class="active">
        {% else %}
        <li >
        {% endif %}
            <a href="{% url 'Admin:tags' %}">Tags</a>
        </li>
        {% if 'upload/' in request.path %}
        <li class="active">
        {% else %}
        <li>
        {% endif %}
            <a href="{% url 'Admin:upload' %}">Uploads</a>
        </li>
        {% if 'about/' in request.path %}
        <li class="active">
        {% else %}
        <li>
        {% endif %}
          <a href="{% url 'Admin:about_edit'%}">About</a>
        </li>

</ul>

<ul class="nav navbar-nav navbar-right">
    {% if user.username == Node or user.username == '' %}
        <li><a href="{%url 'Admin:login' %}">Login</a></li>
    {% else %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                    aria-expanded="false">
                {{ user.username }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'Admin:logout' %}">Logout</a></li>
            </ul>
        </li>
    {% endif %}
</ul>