MyPersonal/About/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from. views import about

urlpatterns = [
    url(r'^$', about, name="about" )
]

MyPersonal/Admin/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import edit_tags, login_views, post_edit, LogoutViews, \
    upload_index, register, post_index, post_create, tag_index, create_tags,\
    about_edit
from django.contrib.auth import views as auth_views
app_name = 'Admin'
urlpatterns = [
    url(r'^$', login_views, name='login'),
    url(r'^login/$',login_views, name='login'),
    url(r'^logout/$',LogoutViews.as_view(), name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^posts$',post_index, name='posts'),
    url(r'^posts/([\d]+)/edit/$',post_edit, name="post_edit"),
    url(r'^posts/create/$', post_create, name='post_create'),
    url(r'^tags/$', tag_index, name='tags'),
    url(r'^create_tags',create_tags,name='create_tags'),
    url(r'^tags/([\d]+)/edit/',edit_tags, name='edit_tag'),
    url(r'^about/edit/', about_edit, name='about_edit'),
    url(r'^upload/$', upload_index, name='upload'),
]

MyPersonal/MyPersonal/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, ShowPostsViews, ContactViews
from django.contrib.auth import views



urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/',ContactViews.as_view(), name='contact'),
    url(r'^posts/(?P<slug>\w+)$', ShowPostsViews.as_view(), name='show'),
    url(r'^admin/', include('Admin.urls')),
    url(r'^about/', include('About.urls')),
    url(r'^uploads/',include('upload.urls')),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
]

handler404 = 'MyPersonal.views.page_not_found_view'
handler403 = 'MyPersonal.views.permission_denied_view'
handler500 = 'MyPersonal.views.error_view'

MyPersonal/Admin/templates/tags/tags_create.html
{% extends "layout.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row page-title-row">
        <div class="col-md-12">
            <h3>Tags <small>» Create New Tag</small></h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">New Tag Form</h3>
                </div>
                <div class="panel-body">



                    <form class="form-horizontal" role="form" method="POST" id="create_tags">
                           {% csrf_token %}
                            <div class="form-group">
                                <label for="tags" class="col-md-3 control-label">Tag</label>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="tags" id="tags" value="{{ tag }}" autofocus>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="meta_description" class="col-md-3 control-label">
                                    Meta Description
                                </label>
                                <div class="col-md-8">
                                    <textarea class="form-control" id="meta_description" name="meta_description" rows="3">{{ meta_description }}
                                    </textarea>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-7 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary btn-md">
                                        <i class="fa fa-plus-circle"></i>
                                        Add New Tag
                                    </button>
                                </div>
                            </div>

                        </form>

                 </div>
             </div>
        </div>
    </div>
</div>
{% endblock %}

MyPersonal/Admin/templates/tags/tags_edit.html
{% extends "layout.html" %}

{% block content %}
 <div class="container-fluid">
        <div class="row page-title-row">
            <div class="col-md-12">
                <h3>Tags <small>» Edit Tag</small></h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Tag Edit Form</h3>
                    </div>
                    <div class="panel-body">
                        {% include 'admin/../partials/success.html' %}

                        <form class="form-horizontal" role="form" method="POST" action="{% url 'Admin:edit_tag' data.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="_method" value="PUT">
                            <input type="hidden" name="id" value="{{ id }}">

                            <div class="form-group">
                                <label for="tag" class="col-md-3 control-label">Tag</label>
                                <div class="col-md-3">
                                    <input type="text" class="form-control" name="tag" id="tag" value="{{ data.tag }}" autofocus>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="meta_description" class="col-md-3 control-label">
                                    Meta Description
                                </label>
                                <div class="col-md-8">
                                    <textarea class="form-control" id="meta_description" name="meta_description" rows="3">{{ data.meta_description }}
                                    </textarea>
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-7 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary btn-md">
                                        <i class="fa fa-save"></i>
                                        Save Changes
                                    </button>
                                    <button type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#modal-delete">
                                        <i class="fa fa-times-circle"></i>
                                        Delete
                                    </button>

                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="modal-delete" tabIndex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        ×
                    </button>
                    <h4 class="modal-title">Please Confirm</h4>
                </div>
                <div class="modal-body">
                    <p class="lead">
                        <i class="fa fa-question-circle fa-lg"></i>
                        Are you sure you want to delete this tag?
                    </p>
                </div>
                <div class="modal-footer">
                    <form method="POST" action="{% url 'Admin:edit_tag' data.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">
                            <i class="fa fa-times-circle"></i> Yes
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

MyPersonal/Admin/templates/tags/tags_index.html
{% extends "layout.html" %}

{% block content %}
<div class="container-fluid">
        <div class="row page-title-row">
            <div class="col-md-6">
                <h3>Tags <small>» Listing</small></h3>
            </div>
            <div class="col-md-6 text-right">
                <a href="{%url 'Admin:create_tags' %}" class="btn btn-success btn-md">
                    <i class="fa fa-plus-circle"></i> New Tag
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                    {% include 'admin/../partials/success.html' %}
                <table id="tags-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Tag</th>
                            <th class="hidden-md">Meta Description</th>
                            <th data-sortable="false">Actions</th>
                        </tr>
                     </thead>
                    <tbody>
                    {% for tag in tags %}
                        <tr>
                            <td>{{ tag.tag }}</td>
                            <td class="hidden-md">{{ tag.meta_description }}</td>
                            <td>
                                <a href="{% url 'Admin:edit_tag' tag.id %}" class="btn btn-xs btn-info">
                                    <i class="fa fa-edit"></i> Edit
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(function() {
            $("#tags-table").DataTable({
            });
        });
    </script>
{% endblock %}